### ISSUE TITLE
Low-resolution icon appears blurry in HiDPI screens

### ISSUE THREAD

**Issue by jmgomezpoveda** [Dominique92/ol-geocoder#102]
The icon provided has a low resolution, and therefore appears blurry when viewed in HiDPI screens. This contrasts with the other, sharper icons.

![no-hidpi](https://cloud.githubusercontent.com/assets/3722516/20857892/e96a4aa8-b930-11e6-836a-f7b8f45daf06.png)

**Comment by jmgomezpoveda** [comment]
As an alternative to using the icon, one can also use the unicode search character:

```
.ol3-geocoder-btn-search {
    background-image: none;
}
.ol3-geocoder-btn-search:before {
    content: '🔍';
    font-size: 0.7em;
    line-height: 0.8em;
}
```

![unicode-search](https://cloud.githubusercontent.com/assets/3722516/20858031/c80f9604-b932-11e6-85f1-0537c9dcaa66.png)

**Comment by jmgomezpoveda** [comment]
Optionally, in case you prefer the old icon for non-HiDPI devices, this icon could be used only in HiDPI devices using media queries:

```
@media only screen and (-webkit-min-device-pixel-ratio: 1.3),
only screen and (-o-min-device-pixel-ratio: 13/10),
only screen and (min-resolution: 120dpi) {
	.ol3-geocoder-btn-search {
	    background-image: none;
	}
	.ol3-geocoder-btn-search:before {
	    content: '🔍';
	    font-size: 0.7em;
	    line-height: 0.8em;
	}
}
```

**Comment by jonataswalker** [comment]
@jmgomezpoveda 
Sorry the delay, I'm right now in a hurry and ASAP will give it a closer look.

**Comment by jonataswalker** [comment]
@jmgomezpoveda 

Are you able to prepare a PR with your suggestions?

**Comment by jmgomezpoveda** [comment]
I am afraid this may not work with 2.4.0, due to the styling changes. Will need to analyse the impact to port it to 2.4.0.
