### ISSUE TITLE
Narrow down the results to cities or countries?

### ISSUE THREAD

**Issue by karakostis** [Dominique92/ol-geocoder#145]
Is it possible to narrow down the results to cities or countries? For example for the OSM geocoder there is a featuretype parameter: https://help.openstreetmap.org/questions/27915/how-to-narrow-the-result-from-nominatim-with-only-cities-and-countries-no-additional-areas

**Comment by jonataswalker** [comment]
Yes for countries, with OSM and Maquest. See API Docs for `constructor`.

```javascript
var geocoder = new Geocoder('nominatim', {
  provider: 'osm',
  countrycodes: 'gb', // https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
});
```

PR welcome for cities!

**Comment by karakostis** [comment]
Thanks. 
What I meant is to be able to search only for countries or cities. Right now the results go down to the level of streets, airports etc. I read here [https://help.openstreetmap.org/questions/31629/restricting-nominatim-search-results-to-a-certain-adminstrative-level](url)  that its possible to use the featureType parameter but it doesn't seem to respond.

Great work. Really appreciate it.

**Comment by Dominique92** [comment]
Is it totally solved ?
Still interested to search only for countries or cities.?

**Comment by Dominique92** [comment]
Closed because no more request at the moment
Feel free to reopen it if necessary.
