### ISSUE TITLE
customised addressTemplate function ?

### ISSUE THREAD

**Issue by Jens-dojo** [Dominique92/ol-geocoder#183]
Hello,

I would like to have a customised addressTemplate() function.
How can I patch it?
As far as I see there is no possibility to patch it from the outside ?!
Thank you
J

**Comment by jonataswalker** [comment]
You're right, there's no way actually. Would you like to provide a PR?

**Comment by Dominique92** [comment]
Closed because no more request at the moment
Feel free to reopen it if necessary.
