### ISSUE TITLE
Is there a way to get keyboard return event to pick top choice in dropdown?

### ISSUE THREAD

**Issue by bwhitney** [Dominique92/ol-geocoder#206]
Like your geo-coder, but it would be nice for a user to just type in a name (including in auto-complete mode) and hit keyboard return/enter in the input box and have the address default to the top one in the dropdown list rather than having to click.

Is there currently a way to do this using options?  Have played around w/out success so thinking not.  If not, any chance this could be an enhancement?

**Comment by jonataswalker** [comment]
For sure, this a great feature to be done. Just can't tell about a schedule ok?

**Comment by rasa2k** [comment]
You could consider making the ul result list a datalist instead and get the keyboard support out-of-box. Biggest downside is the styling of it.

**Comment by Dominique92** [comment]
Closed in v4.3.1
Use option limit: 1,
