### ISSUE TITLE
input search bar 

### ISSUE THREAD

**Issue by ahlem17** [Dominique92/ol-geocoder#222]
Hi, there is a simple way to create two input text for searching (one to search depart point address other for arrived point address) or a way to create 2 externals element input text and related them with the plugin?

**Comment by jonataswalker** [comment]
Related #87 

I think this specific request goes beyond the scope of this plugin but you could create a static demo so we can understand it better.

**Comment by ahlem17** [comment]
I'm looking to create model like this search bar of OSRM http://map.project-osrm.org/?z=7&center=50.004209%2C11.997070&hl=fr&alt=0&srv=1

**Comment by Dominique92** [comment]
Hello everyone,
I understand that this feature can be useful. But it's a complex feature that will require complex coding and interface layout.
Do more of you need this feature?

**Comment by Dominique92** [comment]
Closed because no more request at the moment
Feel free to reopen it if necessary.
