### ISSUE TITLE
ol-geocoder results are too much zoomed -in

### ISSUE THREAD

**Issue by MShrivastava-RMS** [Dominique92/ol-geocoder#235]
I am using  ol-geocoder 4.1.2. The results are too much zoomed in .
I have followed https://jsfiddle.net/jonataswalker/c4qv9afb/
In the fiddle above, the results are at a suitable zoom level.
I have used "view.setZoom(12)" , the results are unaffected.

**Comment by kirtan-desai** [comment]
put preventDefault option to true.

and then

```javascript
geocoder.on('addresschosen', function (evt) {
   map.getView().setZoom(12)
});
```

**Comment by Dominique92** [comment]
I have corrected this in https://github.com/Dominique92/ol-geocoder

This bug occurs when the provider returns a coordinate but no bbox.
I have corrected this & provided an option
  * `defaultFlyResolution` : `1`; (meters per pixel) resolution to fly to when only coords & not bbox is returned by the provider;

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0

**Comment by Dominique92** [comment]
When the provider returns an extent with the location found (country, city, ...), the map is enlarged to this extent.
When the provider returns no extent (simple point of interest), the map is enlarged to the `defaultFlyResolution` option.

If you want the map to be zoomed to another resolution when no extend is returned, you can tune the following Geocoder option:
```
{
    defaultFlyResolution: 10, // Meters per pixel
}
```
Using resolution (meters per pixel) is more accurate than zoom (level of tile count from maximum of displayed layer)
