### ISSUE TITLE
Some 404 errors, unable to access content

### ISSUE THREAD

**Issue by thomasdowding** [Dominique92/ol-geocoder#236]
Sorry if this is a beginner question!

Created basic page with standard OpenLayers setup. Added this plugin, tested using both CDN links. Plugin is somewhat functional (no markers or popups, but still zooms to correct location). Following errors in console:

DevTools failed to load SourceMap: Could not load content for https://unpkg.com/ol-geocoder.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

(The next two happen after zooming to the address)

GET file://cdn.rawgit.com/jonataswalker/map-utils/master/images/marker.png net::ERR_FILE_NOT_FOUND

Uncaught ReferenceError: content is not defined
    at e.<anonymous> (main.js:31)
    at e.dispatchEvent (Target.js:114)
    at nt.chosen (ol-geocoder:7)
    at HTMLLIElement.<anonymous> (ol-geocoder:7)

(main.js is my own file, which has a reference to content, based only on the code provided in README).

I tried downloading the plugin myself, but couldn't find any files named "ol-geocoder.js.map".

**Comment by Dominique92** [comment]
The mapfile load doesn't work with the script shortcut https://unpkg.com/ol-geocoder
Use https://unpkg.com/ol-geocoder@latest/dist/ol-geocoder.js
This will enable the load of the map file https://unpkg.com/ol-geocoder@latest/dist/ol-geocoder.js.map
