### ISSUE TITLE
Is the timeout necessary?

### ISSUE THREAD

**Issue by alexthefifth** [Dominique92/ol-geocoder#240]
In many of the examples there is a timeout of 3000ms used. Is this a necessary/functional delay (maybe waiting for API response from the geocoder?) or is this a cosmetic/aesthetic thing?

**Comment by Dominique92** [comment]
Yes, the timeout is necessary because, if we display the popup before the end of the span (500 ms), the span stops where it is.
We can set the timeout at something like 500 ms + a bit of spare.
