### ISSUE TITLE
Firefox console issue TypeError

### ISSUE THREAD

**Issue by AllroadsNL** [Dominique92/ol-geocoder#241]
In firefox i get this message:  Uncaught TypeError: t.ol is undefined
ol-geocoder:11:485
[file](https://cdn.jsdelivr.net/npm/ol-geocoder)

"ol/Feature","ol/proj"],e):(t="undefined"!=**typeof globalThis?globalThis:t||self)**.Geocoder=e(t.ol.control.Control,

and with
[link](https://unpkg.com/ol-geocoder) directed to
[file](https://unpkg.com/ol-geocoder@4.1.2/dist/ol-geocoder.js)
Uncaught TypeError: t.ol is undefined
ol-geocoder:7:485

"ol/Feature","ol/proj"],e):(t="undefined"!=**typeof globalThis?globalThis:t||self)**.Geocoder=e(t.ol.control.Control,

Just let you know, I saw ..............

V4.1.2

**Comment by Dominique92** [comment]
No more following. I hope it works now.
