### ISSUE TITLE
Using Search Function Outside Div

### ISSUE THREAD

**Issue by ghost** [Dominique92/ol-geocoder#247]
Hi, is there a way to put the search function outside the Openlayers function?
Picture 1: Outside the function
![1](https://user-images.githubusercontent.com/91780776/162642956-16a9518d-f742-44b5-985b-d7644723b06a.JPG)
Picture 2: Inside the function
![2](https://user-images.githubusercontent.com/91780776/162642972-bad161b4-4138-44d3-9398-f09455e1d472.JPG)

      const mapTemp = new OlMap({
        target: mapElement.current,
        controls: defaultControls().extend([
          new ZoomSlider(),
          new Geocoder('nominatim', {
            provider: 'osm',
            key: '__some_key__',
            lang: 'pt-BR',
            placeholder: 'Search for ...',
            targetType: 'text-input',
            limit: 5,
            keepOpen: true
          })
        ]),
        view: new OlView({
          center: fromLonLat([108.68593,3.747128]),
          zoom: 5,
          minZoom: 2,
          maxZoom: 18,
        }),

But use the function outside like this:

`  function Home() {
    const [map, setMap] = useState(null);
    return (
      <div>
        <Homez map={map}/>
        <Map returnRef={setMap} />
      </div>
    );
  }`

**Comment by Dominique92** [comment]
I have provided this in https://github.com/Dominique92/ol-geocoder
You can do this with a bit of css & js
See : https://dominique92.github.io/ol-geocoder/examples/external-div.html

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
