### ISSUE TITLE
Warning when using ol-geocoder from the CDN

### ISSUE THREAD

**Issue by kirtan-desai** [Dominique92/ol-geocoder#250]
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/ol-geocoder.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by AdityaaBangari** [comment]
did you find a solution for this

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0

This doesn't work with the shortcut https://cdn.jsdelivr.net/npm/ol-geocoder
Use https://cdn.jsdelivr.net/npm/ol-geocoder/dist/ol-geocoder.js
This will load the map file https://cdn.jsdelivr.net/npm/ol-geocoder/dist/ol-geocoder.js.map
