### ISSUE TITLE
Search Button - search does not work from smartphone if there is another text field

### ISSUE THREAD

**Issue by andreaordonselli** [Dominique92/ol-geocoder#255]
The search works fine on a pc.
But in the smartphone when I type a text and press enter the search is not performed because in my map I have another visible text field, so the enter key moves the cursor to this next text field and the search is not performed.
A solution could be the introduction of an "arrow" type "send button" in the geocoder, perhaps to be positioned after the "x" of the gcd-input-reset.
Can you help me to create it?

**Comment by andreaordonselli** [comment]
I solved it by myself by activating the option

`autoComplete: true;`

In doing so there is no need to press enter after typing some text but a drop-down menu of results exits as you type.
Thanks for the plugin.
Greetings.

**Comment by mtmail** [comment]
Using auto-complete for the default provider (osm) is against the provider’s terms https://operations.osmfoundation.org/policies/nominatim/ Searching for “Washington, DC” would lead to 12 API requests.

**Comment by Dominique92** [comment]
As auto-complete was only implemented for nominatim, I completely removed these options
Anyway, this network ressource consuming. Let's save the planet.

Also, I did not put a second button in the input field who may be dissicults to touch on little terminals, considering that empty the feild can be done some other ways, I replaced the erase button by send.
This is not yet published in nmp but you can test it with :
```html
<link rel="stylesheet" href="http://dominique92.github.io/ol-geocoder/dist/ol-geocoder.css">
<script src="http://dominique92.github.io/ol-geocoder/dist/ol-geocoder-debug.js"></script>
```
Solved in https://github.com/Dominique92/ol-geocoder

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0

**Comment by andreaordonselli** [comment]
Thanks, your solution works perfectly.

**Comment by andreaordonselli** [comment]
Thanks, your solution works perfectly. I integrated it into my project which is currently built with openlayers 6.15.1
See https://www.opengis.it/demo/

**Comment by Dominique92** [comment]
Thank you for the feed-back.
I am proud to have contributed.
