### ISSUE TITLE
Remove search layer from legend

### ISSUE THREAD

**Issue by andreaordonselli** [Dominique92/ol-geocoder#256]
I use the ol-ext layerswitcher and this geocoder.
However following the search with geocoder in the legend the visible layer appears at the top.
![image](https://user-images.githubusercontent.com/89784373/186660288-50232d04-9a92-4627-8be3-493fbc6074d3.png)

The layerswitcher has a setting `displayInLayerSwitcher : false,` to be written in `ol.layer.Vector ({`
I don't understand how to edit ol-geocoder.js to insert the setting.
Can you help me?
Thank you

**Comment by andreaordonselli** [comment]
I found a solution by myself.
You need to enter `displayInLayerSwitcher: false` at this point:

`this.layer = new n ({name: this.layerName, source: new s, displayInLayerSwitcher: false,})`

**Comment by Dominique92** [comment]
I have provided this in https://github.com/Dominique92/ol-geocoder

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
