### ISSUE TITLE
"countrycodes" option broken with array

### ISSUE THREAD

**Issue by immanuel-h** [Dominique92/ol-geocoder#257]
Config: `countrycodes: ["at", "de"]` (as per doc, array of iso country codes)

Expected: URL generated as `countrycodes=at,de`

Actual: Url generated as `0=at&1=de`

Source of the problem: [toQueryString method](https://github.com/jonataswalker/ol-geocoder/blob/e5ae7721255c75b644103746a2dc812b33255850/src/helpers/ajax.js#L21)

Minimal test case
```
toQueryString({countrycodes:["at", "de"]})
> '0=at&1=de'
```

Workaround: using a comma-separated string instead of an array (i.e. `countrycodes:"at,de"`)

If this is intended behavior the docs should be updated.

**Comment by mtmail** [comment]
`countrycodes=at,de` is correct. Uppercase works but inside the Nominatim database the codes are stored lowercase so we usually write them lowercase in documentation.
