### ISSUE TITLE
Broken on Openlayers 7.1.0

### ISSUE THREAD

**Issue by geraldo** [Dominique92/ol-geocoder#258]
Since updating to latest OL 7.1.0 i get the following error in the console:

`Uncaught TypeError: class constructors must be invoked with 'new'`

**Comment by fogracvxy** [comment]
Yea getting the same error

**Comment by kirtan-desai** [comment]
Same thing happened with [ol-layerswitcher](https://github.com/walkermatt/ol-layerswitcher/issues/487). The solution seems to be removing the webpack transpiling ES6 classes to ES5. Would be great if anyone can make a PR. Can take a look at [this commit](https://github.com/walkermatt/ol-layerswitcher/commit/85f7957abb5e353a27674d65361f4b399c7ab7dd) for reference.

**Comment by Dominique92** [comment]
Workaround:
Use ol-geocoder-debug.js and replace line 1134 by:
      return new Control({ element: this.container });

**Comment by kirtan-desai** [comment]
I am working on the issue. The Base class in base.js calls super after accessing "this" which throws an error in ES6. Trying to refactor that.

**Comment by kirtan-desai** [comment]
Any suggestions how to refactor it?

**Comment by Dominique92** [comment]
Something in there ? https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

**Comment by walkermatt** [comment]
@Dominique92 perhaps try disabling transpiling by commenting out the buble plugin in https://github.com/jonataswalker/ol-geocoder/blob/master/build/config.js#L54

**Comment by fogracvxy** [comment]
> I am working on the issue. The Base class in base.js calls super after accessing "this" which throws an error in ES6. Trying to refactor that.
> 
> EDIT: Done with this. ol-geocoder will now ship with ES6 classes. Will make a PR. Only issue I'm facing now is that the magnifying glass is not visible on the button since OL7 has default white background for colors. Will try to change color of magnifying glass.

Thanks for taking a look into it and fixing it :)

**Comment by kirtan-desai** [comment]
> @Dominique92 perhaps try disabling transpiling by commenting out the buble plugin in https://github.com/jonataswalker/ol-geocoder/blob/master/build/config.js#L54

Already did that. It works. Making up a PR after upgrading to v7 in examples

**Comment by fogracvxy** [comment]
> > @Dominique92 perhaps try disabling transpiling by commenting out the buble plugin in https://github.com/jonataswalker/ol-geocoder/blob/master/build/config.js#L54
> 
> Already did that. It works. Making up a PR after upgrading to v7 in examples
> 
> EDIT:
> PR is made. Please review it.

Can't download your repo using `npm install` getting errors with node-sass if installing with "no optional". If I do normal install it gets stuck at fsevents.

**Comment by kirtan-desai** [comment]
I'm able to run ```nom I``` after cloning the repo.

**Comment by fogracvxy** [comment]
> I'm able to run `npm i` after cloning the repo.

I am not sure what is happening with my` npm install https://github.com/kirtan-desai/ol-geocoder.git` stops with fsevents install and hangs there. `npm install https://github.com/kirtan-desai/ol-geocoder.git --no-optional` leaves me with node-sass errors Idk why...

**Comment by Dominique92** [comment]
Anyway, it seems to me more logical to call super first, then to use this:

Doing this:
```
  ...
  this.layer = $nominatim.layer;
  super({ element: this.container });
}
```
If the parent constructor initialize this.layer, you will get his value.

is not the same than:
```
{
  super({ element: this.container });
  this.layer = $nominatim.layer;
  ...
```
you will get your value

Example : https://github.com/openlayers/openlayers/blob/main/src/ol/control/FullScreen.js#L83-L97

**Comment by kirtan-desai** [comment]
> > I'm able to run `npm i` after cloning the repo.
> 
> I am not sure what is happening with my` npm install https://github.com/kirtan-desai/ol-geocoder.git` stops with fsevents install and hangs there. `npm install https://github.com/kirtan-desai/ol-geocoder.git --no-optional` leaves me with node-sass errors Idk why...

installing with npm directly is also working for me. why don't you try cloning the repo and running it?

**Comment by kirtan-desai** [comment]
@Dominique92  Did you take a look at my PR #259?

**Comment by Dominique92** [comment]
> @Dominique92 Did you take a look at my PR #259?

Sorry ! It's super :)
Awaiting the dist (I don't use npm)

**Comment by kirtan-desai** [comment]
> > @Dominique92 Did you take a look at my PR #259?
> 
> Sorry ! It's super :) Awaiting the dist (I don't use npm)

Just clone the repo, run ```npm i``` and then run ```npm run build```. You'll get the files in dist folder.

**Comment by Dominique92** [comment]
> Just clone my repo, run `npm i` and then run `npm run build`. You'll get the files in dist folder.

Sorry, I use Windows where npm is a mess, not linux
I will wait the dist

**Comment by kirtan-desai** [comment]
> > Just clone my repo, run `npm i` and then run `npm run build`. You'll get the files in dist folder.
> 
> Sorry, I use Windows where npm is a mess, not linux I will wait the dist

I don't know when my PR will be reviewed. Till then, [here](https://github.com/kirtan-desai/ol-geocoder-5-dist) are the dist files. Let me know if there's any issue.

**Comment by Dominique92** [comment]
> Till then, [here](https://github.com/kirtan-desai/ol-geocoder-5-dist) are the dist files. Let me know if there's any issue.

Thank you. This dist works perfectly for me.

**Comment by kirtan-desai** [comment]
Is this repo maintained anymore? Should I publish a package of my forked repo as ol-geocoder v5?

**Comment by kirtan-desai** [comment]
Hey guys, I have published my forked repo of ol-geocoder which is compatible with openlayers 7. I'll be maintaining the fork. https://www.npmjs.com/package/@kirtandesai/ol-geocoder

**Comment by kirtan-desai** [comment]
Hey Massimo, feel free to make this as a PR on my fork.
