### ISSUE TITLE
Limit search result to city

### ISSUE THREAD

**Issue by geraldo** [Dominique92/ol-geocoder#260]
What would it take to extend the plugin with an option to limit search results to cities, for example named `citycodes`?

Nominatim has an option for this called `city=<city>` as explained [here](https://nominatim.org/release-docs/latest/api/Search/#parameters), so that seems possible adding it to OSM provider.

I also saw `viewbox` parameter in [ol-ext SearchNominatim control](https://viglino.github.io/ol-ext/doc/doc-pages/ol.control.SearchNominatim.html), so another option would be to add an `extent` parameter.

**Comment by Dominique92** [comment]
[nominatim doc](https://nominatim.org/release-docs/latest/api/Search/#result-limitation)  does not specify  `citycode` as a limitation parameter

I have provided the `viewbox` parameter in https://github.com/Dominique92/ol-geocoder

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
