### ISSUE TITLE
Allow custom URL for osm provider

### ISSUE THREAD

**Issue by syncush** [Dominique92/ol-geocoder#266]
It would be awesome if I would be able to use the `osm` provider with my custom nominatim deployment and not the public API.

I would be happy to contribute, if you accept this request.

**Comment by andreaordonselli** [comment]
Hello, thanks for the commit. Can you explain to me how it works?
Are you running the jonataswalker project in parallel or did you start from a specific version and break away by updating only your repository?
I see that jonataswalker updated some stuff 2 weeks ago, are the updates made by him reflected in your repository as well?
How do I figure out which repository is right for me? Right now this by jonataswalker works fine in my openlayers 6.15.1 project.
Then how do I figure out what features your repository has more than this?
Thank's for your job.

**Comment by Dominique92** [comment]
Hi. This is a good question and needs some clarification.
Jonatas recently pushed a blocking change related to a modification of the nominatim/osm interface but I fear that he will not maintain more.
Jonatas has requested a maintenance takeover, which I am willing to do.
While waiting for his response, I published my version which I maintained in a private repository, being a candidate to become the official version.
Unfortunately I just tested it on openlayers 6.15.1 but it fails. I will investigate and support it soon but it is not available yet.
Additionally, I'm working to deliver my package on npm.
For these reasons, it is best that you continue with the Jonatas repository a little bit and see what happens to mine, including reports from other users.
Thank you for your feedback, it is very useful and do not hesitate to ask me further.

**Comment by Dominique92** [comment]
Hi everybody.
Everything evolved quickly.
Jonatas transferred ol-geocoder to my Dominique92 account
So there is only one left: https://github.com/Dominique92/ol-geocoder
Changes made previously to my repository are canceled. I will put them back gradually.

**Comment by andreaordonselli** [comment]
Congratulations on getting the repository. Don't forget to mention @jonataswalker on the home page.

First of all, I draw your attention to this [issue ](https://github.com/Dominique92/ol-geocoder/issues/255) that has not yet been resolved; where a user has demonstrated a violation of the nominatim's terms. Subsequently, following my report, Viglino also updated its library ol-ext.
I think it is appropriate to disable the autocomplete for nominatim and resolve the sending from the smartphone keyboard in another way.

Greetings and congratulations again.

**Comment by mtmail** [comment]
Thanks to raising the issue again. Yes, Nominatim can't do autocomplete, for the search "Londo" it will never return "London". We usually tell people to use photon instead (which in turn imports Nominatim data).

**Comment by andreaordonselli** [comment]
Thank you for your answer. Nominatim can do autocomplete. If you now write `autocomplete: true`, the search shows result previews like this screen
![image](https://github.com/Dominique92/ol-geocoder/assets/89784373/449828dd-35ed-43d7-adc5-f07d303559d8)

But this violates terms. I advise Dominiq to deactivate this option for nominatim, now it can be activated.

**Comment by mtmail** [comment]
Yes, should be deactivated.

**Comment by Dominique92** [comment]
Thanks for the comments & the heads up. This is very usefull as this topic was closed & I did not have it in the issues queue.
Also because this sowtware covers a huge domain & Apple folks are part of my weaknesses.
I do agree with your remarks & I will work on it soon.

But, please, follow up this subject on the dedicated issue https://github.com/Dominique92/ol-geocoder/issues/255
I just reopened it.

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
