### ISSUE TITLE
Init error on 4.2.0

### ISSUE THREAD

**Issue by Dominique92** [Dominique92/ol-geocoder#270]
I get an error while initialising the geocoder :
`base.js:49 Uncaught TypeError: Class constructor ca cannot be invoked without 'new'`

See on this trivial exemple using openlayers 7.5.1 & geocoder 4.2.0
http://localhost/dev/geocoder420loaderror/fail.html

I don't know if is related & I did not succceed to make it working but the base class seems to not match the new JS requirements to not use this before super
```
    this.options = mergeOptions(DEFAULT_OPTIONS, options);
    this.container = undefined;
. . .
    super({ element: this.container });
}
```
Can it be a babel missing transpiler related to this ?

**Comment by ElisabettaPed** [comment]
Hi, I've the same error using the map in angular project, have you found a solution?
"ol": "7.5.1",
"ol-geocoder": "4.2.0",
this is my code:

`import Geocoder from 'ol-geocoder';`
`...`
```
let provider = new StreetProvider();
const geocoder = new Geocoder('nominatim', {
    provider: provider,
    //key: '__some_key__',
    lang: 'it-IT',
    placeholder: 'Search for ...',
    targetType: 'text-input',
    limit: 5,
    keepOpen: true
});
this.map.addControl(geocoder);
```

error: 
ERROR TypeError: Class constructor Control cannot be invoked without 'new'
    at new e (ol-geocoder.js:7:16533)
    at OlMapComponent.ngAfterViewInit (ol-map.component.ts:161:26)
    at callHook (core.mjs:2495:22)
    at callHooks (core.mjs:2464:17)
    at executeInitAndCheckHooks (core.mjs:2415:9)
    at refreshView (core.mjs:12055:21)
    at refreshComponent (core.mjs:13080:13)
    at refreshChildComponents (core.mjs:11774:9)
    at refreshView (core.mjs:12034:13)
    at refreshEmbeddedViews (core.mjs:13034:17)

**Comment by Dominique92** [comment]
Hello everybody.
I have setup a new repository https://github.com/Dominique92/ol-geocoder in order to be candidate to the maintenance take over of ol-geocoder.
As it, it runs with Openlayers 5.7.1
You can use the /dist/ol-geocoder.* files & see demos on /example/*.html
I have simplified the build to avoid the bunch of deprecated packages that I was unable to make working on my server.
A lot of is left to do to be at that level of the existing package (including npm delivery) but I will work hard to achieve this.
Fell free to use it & provide comments, improvements, issues & push.

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
