### ISSUE TITLE
Announcement: Transfer of Repository Ownership

### ISSUE THREAD

**Issue by jonataswalker** [Dominique92/ol-geocoder#275]
I hope this message finds you well.
I want to express my gratitude for your support and contributions to this project over the years.

For the sake of this project's growth I'm transferring the ownership to @Dominique92.

**What does this mean for you?**

**Continuity**: Rest assured that the project will continue to thrive under new ownership. The core goals and values of the project will remain intact.

**Contributions**: Your contributions, bug reports, and feature requests are still valued and welcome. The new maintainer will actively engage with the community and continue to review and merge pull requests.

**Comment by Dominique92** [comment]
Hello everybody!

As @jonataswalker said, I have the honor of taking over maintenance of ol-geocoder. Thank you for your confidence.
I would like first to thank him & all the initial team for the tremendous work done up to now. A big thank you to @kirtandesai who supported if by a year & did a very good job cleaning build & test that was decisive to help for the takeover.

ol-geocoder is a very important piece of the Openlayers biotope, the best & more complete of the available geocoders, used by many sites & users that we need to keep alive.
As @jonataswalker said, I engage to maintain the core goals and values of this project.

Now, come to the next. I propose to focus on:
- Customer first :
ol-geocoder is not a simple piece of software or a new project that we start with a pair of friends. It is a functionality daily used by thousands of persons for their all-day life.
We do need to drive our work by their needs first. That's a point where we will need active feedback from any webmaster or developer having contact with final users.

- Stability :
For the same reason, we must ensure that all the functionalities are stable on all supported platforms.
As the dev team cannot test on all field environment, any information from the reality is precious.

- Teamwork :
ol-geocoder is a huge project covering many domains & requiring various skills that you can bring if you are reading these lines. The everybody’s contribution is welcome, at 3 levels, depending on your technical level & availability :
-> Simple information, problem, evolution written in simple English, but as precise as possible with context, examples, details. No problem if you can’t help at the code level, another can come & continue the job.
-> Raise “issues”, precisely describing a bug or required feature at the code level.
-> The best would be to submit a “pull request”. This requires elevated skills, developer environment & a bit of time but, if you can do this, it's the more efficient way to contribute.
Any level of help will be welcome, don't hesitate to give your feedback with your knowledge & resource, the lesser can be decisive.

- Simplicity :
ol-geocoder is in a maintenance phase & will need support over years. If we want to attract new resources, we need to keep it at the minimum the required skills.
Also, the web technology changes at a frenetic rate & software obsolescence is a major risk for us.
For these reasons, we need to keep the code, tools, languages & dependencies as simple as possible.

I will come back on these pages with topics for discussion.
Feel free to comment, make suggestion, participate. The next is on your hands.

Dominique
