### ISSUE TITLE
How to customize original css style for geocoder text-input?

### ISSUE THREAD

**Issue by ericzdj0522** [Dominique92/ol-geocoder#281]
Hello, a quick question: Once I load geocoder into a input-text, how do I override original ol-geocoder.css to change text input width or height? Thanks

**Comment by Dominique92** [comment]
Hello.
You can customize the text-input by overloading the .gcd-txt-control class & the included elements (.gcd-txt-control label, input, button)
Don't forget !important to force overload.

`.gcd-txt-control {
  height: 45px !important;
  width: 200px !important;
}`
`.gcd-txt-control input {
  top: 8px !important;
}`

**Comment by ericzdj0522** [comment]
Thank you sir, one more quick question, once I projected ol-geocoder into a html text-input, can I modify other attribute of that control? like default value for input

**Comment by Dominique92** [comment]
In the Geocoder declaration, to initialise the placeholder (message when the input is empty)
`const geocoder = new Geocoder('nominatim', {placeholder: 'Search in OSM',});`

After the Geocoder is declared, find the input element
`const input = geocoder.element.querySelector('input');`
To replace the placeholder : `input.placeholder ='Bla Bla';`
To add default value (that will be used as search value) : `input.value ='Somewere';`

**Comment by ericzdj0522** [comment]
Thank you for your quick response sir, I'm developing a open source map app platform for our GNSS service, your tool is super brilliant and helpful!❤️

**Comment by Dominique92** [comment]
Your gratitude goes to @jonataswalker and the entire team who developed it.
I'm just glad to support this package now.
