### ISSUE TITLE
The marker is an external dependency

### ISSUE THREAD

**Issue by DC92** [Dominique92/ol-geocoder#285]
The marker is fetched from
`//cdn.rawgit.com/jonataswalker/map-utils/master/images/marker.png`

Use inline code instead as:
`data:image/svg+xml;charset=utf-8,
<svg width="26" height="42" viewBox="0 0 26 42" xmlns="http://www.w3.org/2000/svg">
<polygon points="1,18 14,42 25,18" fill="rgb(75,75,75)" />
<ellipse cx="13" cy="13" rx="13" ry="13" fill="rgb(75,75,75)" />
<ellipse cx="13" cy="14" rx="6" ry="6" fill="yellow" />
</svg>`

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.3
