### ISSUE TITLE
README mentions re-release due to virus, but referenced version not in the list of releases

### ISSUE THREAD

**Issue by StuffOfInterest** [Dominique92/ol-geocoder#291]
The README file says that version 4.3.4 was released due to a virus being included with 4.3.3.  The release list in the repo and npm both show 4.3.3 as the latest version.  This causes concerns for security conscious users when there is mention of a virus and the version listed as current is the one said to have a virus.

Details on how to know if the version in use has the virus would be helpful.

**Comment by Dominique92** [comment]
Thank you for the warning.
There is actually no known virus at all in any ol-geocoder version.
There is no confusion on the npm devileries but, you are right, there is a wrong alert in Github.
I was wrongly allerted by one of my test PC that was infected but this has never impacted the production chain.
