### ISSUE TITLE
reverse geocoding

### ISSUE THREAD

**Issue by ibnubay** [Dominique92/ol-geocoder#86]
This plugin support reverse geocoding?
from lat lon, i can get address name...

Thanks

**Comment by jonataswalker** [comment]
Not yet, but it is intended to support.

I would have some work to do and perhaps was just waiting someone to ask. Keep an eye on it.

**Comment by ibnbay99** [comment]
is This plugin support reverse geocoding already in latest release? v2.4.0

**Comment by allenhwkim** [comment]
FYI, for anyone who is interested in the reverse geocoding, I have some code here, https://github.com/allenhwkim/geocoder/blob/master/src/providers/google.ts#L50. Feel free copy/paste from this repo. https://github.com/allenhwkim/geocoder

**Comment by jonataswalker** [comment]
PR welcome!

@allenhwkim would you able to make this happen?

**Comment by TheGrave** [comment]
I see it has been quite a while. Has this feature fallen out of the roadmap?

**Comment by TheGrave** [comment]
@jonataswalker Another 3 years have passed, gotta ask again :) I see there is maybe some sort of an enhancement cause when I put GPS coordinates as an input now I get the closest town which is not that bad but still far away from what is desired.

**Comment by Dominique92** [comment]
No, this pluggin doesn't implement reverse geocoding & has no intent to do.
