### ISSUE TITLE
search form outside map

### ISSUE THREAD

**Issue by ibnubay** [Dominique92/ol-geocoder#87]
How i can search using existing input text then show result on difference div ?
Note: search form and result place outside map.

**Comment by jonataswalker** [comment]
I have to re-write the html part and come up with a PR to address this issue and #60.

Hold on.

**Comment by abydahana** [comment]
Hello, have add this feature now? Where i can get example?

**Comment by adrianratajczak** [comment]
Hi, what about this feature? I can see that there is a targetType option but it looks like it doesn't work

**Comment by Dominique92** [comment]
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0
